default:
    proso_models:
        random_test:
            nth: 10
        predictive_model:
            class: proso.models.prediction.PriorCurrentPredictiveModel
        mastery_threshold: 0.9
        practice:
            common:
                set_length: 10
                question_queue_size_max: 1
                question__queue_size_min: 1
                save_answer_immediately: false
                queue_length: 10
    proso_common:
        logging:
            js_errors: true
    proso_feedback:
        domain: matmat.cz
        to: [matmat@googlegroups.com]